### ISSUE TITLE
Discover page issues

### ISSUE THREAD

**Issue by kaskil12** [VetleViking/CarSpottingApp#17]
Theres no way to see other spots. If there is a way then its not user friendly. Why not add this?
Fix now pwease!

**Comment by VetleViking** [comment]
Hey! Links to other spots will work, however, there is no support for browsing others spots yet. It is planned to add soon, i will keep this issue updated :)

**Comment by VetleViking** [comment]
found a bug with viewing other spots that made them not be sent from the server, its fixed now

**Comment by kaskil12** [comment]
Fast and informant response :) I am quite ecstatic for the browsing of other car spots function and cant wait to see it!
Could you perhaps send a link of one of your spots as i would like to see a cool car?

Yours sincerely Kasper Kilde <3

**Comment by VetleViking** [comment]
no problem, happy to help! you can see all my spots [here](http://spots.vest.li/makes?username=Vetle)

**Comment by VetleViking** [comment]
A discover page has now been added, you can visit it [here](http://spots.vest.li/discover) or through the button at the home page. 

Please note that the page is still in early development, and will not be perfect. I am aware that the spots takes a while to load, and i am trying to fix it by making a CDN, but it will take some time to implement fully. 

If there are any issues with the page, please let me know :)

**Comment by kaskil12** [comment]
Yippie. Looks good! Would love to see a share button when finding a cool spot on the discover page as well as being able to click the user who has posted something and view their profile. Looking forward to seeing more improvements on the website!
Yours sincerely Kasper Kilde

**Comment by kaskil12** [comment]
When spam clicking the load more spots it says no more spots but if i click it once it works but takes time which is okay but i cant see it loading. So what i would love is something that shows that it is loading

**Comment by kaskil12** [comment]
When liking a spot it likes more than one and i cant just like one without loading ca 3 more

**Comment by VetleViking** [comment]
all of these are fixed as of now :)
